export const IS_LOGIN_FACEBOOK='IS_LOGIN_FACEBOOK';
export const iS_CHANGE_LOGIN_FACEBOOK_INFOR='iS_CHANGE_LOGIN_FACEBOOK_INFOR';
export const IS_LOGIN_USER='IS_LOGIN_USER';
export const ON_CHANGE_LOGIN_USER_INFOR='ON_CHANGE_LOGIN_USER_INFOR';

